[package]
name = "scrape"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.11.10"
scraper = "0.13.0"
# select = "0.6.0-alpha.1"
tokio = { version = "1", features = ["full"] }
comfy-table = "6.0.0-rc.1"
